server:
  port: 8080
spring:
  application:
    name: admin-server
  redis:
    host: 10.8.18.17
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8
    timeout: 100ms
  datasource:
    url: jdbc:mysql://10.8.18.17:3306/db_auth?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoint:
    health:
      enabled: true
